"""
Shared state definitions for LangGraph agents.
"""

from typing import TypedDict, Annotated, Optional, List, Dict, Literal, Any
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import operator


class MissionStatus(str, Enum):
    """Status of an agent mission."""
    PENDING = "pending"
    RUNNING = "running"
    THINKING = "thinking"
    EXECUTING = "executing"
    NEEDS_REVIEW = "needs_review"  # HITL pause
    APPROVED = "approved"
    REJECTED = "rejected"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentType(str, Enum):
    """Types of agents available."""
    JOB_FINDER = "job_finder"
    RESUME_WRITER = "resume_writer"
    APPLICATION = "application"
    LINKEDIN = "linkedin"
    SKILL_GAP = "skill_gap"
    INTERVIEW_PREP = "interview_prep"


@dataclass
class Artifact:
    """An artifact generated by an agent."""
    id: str
    type: str  # pdf, text, json, screenshot
    name: str
    content: Any
    created_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "type": self.type,
            "name": self.name,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class MissionEvent:
    """An event emitted during mission execution."""
    type: str  # status_change, artifact_created, error, log
    message: str
    data: Optional[Dict] = None
    timestamp: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        return {
            "type": self.type,
            "message": self.message,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
        }


class AgentState(TypedDict, total=False):
    """
    Shared state for all LangGraph agents.
    
    This state is passed between nodes and persisted for HITL workflows.
    """
    
    # Mission Identity
    mission_id: str
    user_id: str
    agent_type: AgentType
    
    # Status
    status: MissionStatus
    current_node: str
    progress: int  # 0-100
    
    # Input/Output
    input_data: Dict[str, Any]
    output_data: Dict[str, Any]
    
    # Artifacts
    artifacts: Annotated[List[Artifact], operator.add]
    
    # Events/Logs
    events: Annotated[List[MissionEvent], operator.add]
    
    # Error handling
    error: Optional[str]
    retry_count: int
    
    # HITL
    requires_approval: bool
    approval_reason: Optional[str]
    user_feedback: Optional[str]
    
    # Timing
    started_at: str
    completed_at: Optional[str]
    
    # Agent-specific data (flexible)
    context: Dict[str, Any]


def create_initial_state(
    mission_id: str,
    user_id: str,
    agent_type: AgentType,
    input_data: Dict[str, Any],
) -> AgentState:
    """Create initial state for a new mission."""
    return AgentState(
        mission_id=mission_id,
        user_id=user_id,
        agent_type=agent_type,
        status=MissionStatus.PENDING,
        current_node="start",
        progress=0,
        input_data=input_data,
        output_data={},
        artifacts=[],
        events=[MissionEvent(
            type="status_change",
            message=f"Mission {mission_id} created",
            data={"status": MissionStatus.PENDING.value}
        )],
        error=None,
        retry_count=0,
        requires_approval=False,
        approval_reason=None,
        user_feedback=None,
        started_at=datetime.now().isoformat(),
        completed_at=None,
        context={},
    )


def add_event(state: AgentState, event_type: str, message: str, data: Optional[Dict] = None) -> MissionEvent:
    """Helper to create and add an event to state."""
    event = MissionEvent(type=event_type, message=message, data=data)
    return event


def update_status(state: AgentState, status: MissionStatus, node: str, progress: int) -> Dict:
    """Helper to update mission status."""
    return {
        "status": status,
        "current_node": node,
        "progress": progress,
        "events": [MissionEvent(
            type="status_change",
            message=f"Status changed to {status.value}",
            data={"node": node, "progress": progress}
        )]
    }
